### ISSUE TITLE
Feature: Support for Raw Block Volume Mounts

### ISSUE THREAD

**Issue by davidhalter** [cloudscale-ch/csi-cloudscale#11]
Creating a block volume mount with this driver is currently not possible.

In our case we should at least return `InvalidArgument` if this appears:

https://kubernetes-csi.github.io/docs/raw-block.html#implementing-raw-block-volume-support-in-your-csi-driver

Because we don't return the InvalidArgument there, it can fail pretty randomly with segmentation faults:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x80db26]

goroutine 70 [running]:

github.com/cloudscale-ch/csi-cloudscale/driver.(*Driver).NodeStageVolume(0xc000192150, 0x9b2a60, 0xc0002a8360, 0xc00028c120, 0xc000192150, 0x0, 0x0)

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/driver/node.go:90 +0x3a6

github.com/cloudscale-ch/csi-cloudscale/vendor/github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler.func1(0x9b2a60, 0xc0002a8360, 0x904a20, 0xc00028c120, 0x7f77ad31eb00, 0x0, 0xc0002ba000, 0x0)

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:4929 +0x86

github.com/cloudscale-ch/csi-cloudscale/driver.(*Driver).Run.func1(0x9b2a60, 0xc0002a8360, 0x904a20, 0xc00028c120, 0xc00027a360, 0xc00027a380, 0x893ca0, 0xd70840, 0x9160e0, 0xc0002ba000)

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/driver/driver.go:144 +0x78

github.com/cloudscale-ch/csi-cloudscale/vendor/github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler(0x9113e0, 0xc000192150, 0x9b2a60, 0xc0002a8360, 0xc000288280, 0xc000184100, 0x0, 0x0, 0xc0002bc480, 0x223)

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:4931 +0x158

github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000188180, 0x9b49a0, 0xc00027e300, 0xc0002ba000, 0xc000170570, 0xd47e80, 0x0, 0x0, 0x0)

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc/server.go:966 +0x4a2

github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000188180, 0x9b49a0, 0xc00027e300, 0xc0002ba000, 0x0)

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc/server.go:1245 +0xd61

github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000278030, 0xc000188180, 0x9b49a0, 0xc00027e300, 0xc0002ba000)

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc/server.go:685 +0x9f

created by github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1

/home/dave/go/src/github.com/cloudscale-ch/csi-cloudscale/vendor/google.golang.org/grpc/server.go:683 +0xa1```

When implementing this, please also look out for

```
AccessType: &csi.VolumeCapability_Mount{
    Mount: &csi.VolumeCapability_MountVolume{},
},
```

Also see: https://github.com/digitalocean/csi-digitalocean/issues/192

**Comment by splattner** [comment]
csi-digitalocean has merged support  for Raw Block Volumes into master: See https://github.com/digitalocean/csi-digitalocean/pull/249
